# Generated by Django 5.0.3 on 2024-04-05 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candyland', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='winner',
            new_name='victory',
        ),
    ]
