# Generated by Django 5.0.3 on 2024-04-10 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candyland', '0002_rename_winner_game_victory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='game',
        ),
        migrations.DeleteModel(
            name='player',
        ),
    ]
