# Generated by Django 5.0.3 on 2024-04-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candyland', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='number_players',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='turn',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='ordinal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='skip',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='space',
            field=models.IntegerField(),
        ),
    ]
