# Generated by Django 5.0.3 on 2024-03-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_achievement_leaderboard_userachievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
