# Generated by Django 5.0.2 on 2024-04-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_leaderboard_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
