# Generated by Django 5.0.2 on 2024-04-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_wins'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
