# Generated by Django 5.0.3 on 2024-04-08 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='number_players',
        ),
        migrations.RemoveField(
            model_name='game',
            name='turn',
        ),
    ]
