# Generated by Django 5.0.3 on 2024-04-08 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catan', '0004_game_number_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='corners',
        ),
        migrations.RemoveField(
            model_name='board',
            name='tiles',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Corner',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='Tile',
        ),
    ]
