# Generated by Django 5.0.3 on 2024-04-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catan', '0005_remove_board_corners_remove_board_tiles_delete_game_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yindex', models.IntegerField()),
                ('xindex', models.IntegerField()),
                ('building', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_key', models.UUIDField(unique=True)),
                ('turn', models.IntegerField(default=1)),
                ('number_players', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yindex', models.IntegerField()),
                ('xindex', models.IntegerField()),
                ('terrain', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_key', models.UUIDField(unique=True)),
                ('corners', models.ManyToManyField(related_name='board', to='catan.corner')),
                ('tiles', models.ManyToManyField(related_name='board', to='catan.tile')),
            ],
        ),
    ]
