# Generated by Django 5.0.3 on 2024-04-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catan', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='number_players',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='turn',
            field=models.IntegerField(),
        ),
    ]
