# Generated by Django 5.0.3 on 2024-04-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catan', '0007_corner_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corner',
            name='building',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='corner',
            name='player',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='corner',
            name='xindex',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='corner',
            name='yindex',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tile',
            name='terrain',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='tile',
            name='xindex',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tile',
            name='yindex',
            field=models.IntegerField(default=0),
        ),
    ]
