# Generated by Django 5.0.3 on 2024-04-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catan', '0008_alter_game_number_players_alter_game_turn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_key', models.UUIDField(null=True, unique=True)),
                ('ordinal', models.IntegerField(default=-1)),
                ('wool', models.IntegerField(default=0)),
                ('grain', models.IntegerField(default=0)),
                ('lumber', models.IntegerField(default=0)),
                ('brick', models.IntegerField(default=0)),
                ('ore', models.IntegerField(default=0)),
            ],
        ),
    ]
