# Generated by Django 5.0.3 on 2024-04-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catan', '0009_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='dice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='corner',
            name='building',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='corner',
            name='xindex',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='corner',
            name='yindex',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tile',
            name='xindex',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tile',
            name='yindex',
            field=models.IntegerField(default=0),
        ),
    ]
