# Generated by Django 5.0.3 on 2024-04-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catan', '0010_tile_dice_alter_corner_building_alter_corner_xindex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='build_flag',
            field=models.IntegerField(default=0),
        ),
    ]
