# Generated by Django 5.0.3 on 2024-04-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catan', '0011_game_build_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='setup_flag',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='starting_settlements',
            field=models.IntegerField(default=0),
        ),
    ]
