# Generated by Django 5.0.3 on 2024-04-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catan', '0012_game_setup_flag_player_starting_settlements'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='road_start',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
