# Generated by Django 5.0.3 on 2024-04-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catan', '0013_board_road_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='corner',
            name='player',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='corner',
            name='roads',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
