# Generated by Django 5.0.3 on 2024-04-26 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catan', '0014_corner_player_corner_roads'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='existing_roads',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
