# Generated by Django 5.0.3 on 2024-05-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catan', '0015_board_existing_roads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='game_key',
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(related_name='games', to='catan.player'),
        ),
    ]
