# Generated by Django 5.0.3 on 2024-05-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catan', '0016_remove_player_game_key_game_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='turn',
            field=models.IntegerField(default=0),
        ),
    ]
