# Generated by Django 5.0.3 on 2024-05-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catan', '0017_alter_game_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='turn',
            field=models.IntegerField(default=1),
        ),
    ]
