# Generated by Django 5.0.3 on 2024-05-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catan', '0018_alter_game_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_player',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='previous_player',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='robber_flag',
            field=models.IntegerField(default=0),
        ),
    ]
