# Generated by Django 5.0.3 on 2024-05-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catan', '0019_game_current_player_game_previous_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='robberx',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='board',
            name='robbery',
            field=models.IntegerField(default=0),
        ),
    ]
