# Generated by Django 5.0.3 on 2024-05-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catan', '0020_board_robberx_board_robbery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='robberx',
        ),
        migrations.RemoveField(
            model_name='board',
            name='robbery',
        ),
        migrations.AddField(
            model_name='board',
            name='robber_space',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
