# Generated by Django 5.0.3 on 2024-05-06 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catan', '0022_game_winner_player_cities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='cities',
            new_name='number_cities',
        ),
    ]
