# Generated by Django 5.0.3 on 2024-04-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0003_alter_game_number_players_alter_game_turn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='ordinal',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='player',
            name='space',
            field=models.IntegerField(default=0),
        ),
    ]
