# Generated by Django 5.0.3 on 2024-04-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0004_alter_player_money_alter_player_ordinal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='game_key',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
