# Generated by Django 5.0.3 on 2024-04-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0005_player_game_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='game_key',
            field=models.UUIDField(unique=True),
        ),
    ]
