# Generated by Django 5.0.3 on 2024-04-12 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0006_alter_player_game_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='game_key',
        ),
    ]
