# Generated by Django 5.0.3 on 2024-04-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0008_player_game_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_key', models.UUIDField(unique=True)),
                ('spaces', models.ManyToManyField(related_name='board', to='monopoly.space')),
            ],
        ),
    ]
