# Generated by Django 5.0.3 on 2024-04-16 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0010_space_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('group', models.CharField(max_length=100, null=True)),
                ('prices', models.CharField(max_length=100, null=True)),
                ('rents', models.CharField(max_length=100, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_cards', to='monopoly.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='properties',
            field=models.ManyToManyField(related_name='player_property_hands', to='monopoly.property'),
        ),
        migrations.CreateModel(
            name='PropertyDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('properties', models.ManyToManyField(related_name='property_decks', to='monopoly.property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_cards', to='monopoly.propertydeck'),
        ),
    ]
