# Generated by Django 5.0.3 on 2024-04-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0011_property_player_properties_propertydeck_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='properties',
            field=models.ManyToManyField(related_name='property_hands', to='monopoly.property'),
        ),
    ]
