# Generated by Django 5.0.3 on 2024-04-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0012_alter_player_properties'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='properties',
        ),
        migrations.AddField(
            model_name='property',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='player',
            field=models.IntegerField(default=0),
        ),
    ]
