# Generated by Django 5.0.3 on 2024-04-16 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0016_alter_propertydeck_game_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='deck',
        ),
    ]
